POST   http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt1b2xidW9tIiwiaWQiOiI2YTBlYzAwM2QzYTRkNGFjMDU5MGZlZDUiLCJpYXQiOjE3NzkzNjczNzF9.m1Dndf9gQ80RX8iiz7eaY9F5XlM4qQLN8c1GJcacQZ0

{
 "title": "that's buom",
 "author": "kuol",
 "url":"yes.com"
}